# application-secrets.properties

# JWT Configuration (Dev)
jwt.secret=z8M+P9kL6w5R2NqT4VvY7B9z1A3C5E7G9I1K3M5O7Q9S1U3W5Y7Z9A1B3C5E7G9I
jwt.expiration=86400000

spring.datasource.username=root
spring.datasource.password=root