# MySQL Database (Local)
spring.datasource.url=jdbc:mysql://localhost:3306/bootapplication?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

# JPA/Hibernate (Dev-friendly)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Allowed domain (Local Frontend)
app.cors.allowed-origins=http://localhost:3000,http://localhost:5173