package com.bootcamp4u.serviceImpl;

import com.bootcamp4u.common.BootcampStatus;
import com.bootcamp4u.common.Role;
import com.bootcamp4u.dto.request.BootcampCreateRequest;
import com.bootcamp4u.dto.request.BootcampUpdateRequest;
import com.bootcamp4u.dto.response.BootcampResponse;
import com.bootcamp4u.dto.response.PageResponse;
import com.bootcamp4u.entity.Bootcamp;
import com.bootcamp4u.entity.User;
import com.bootcamp4u.exception.AuthorizationException;
import com.bootcamp4u.exception.DuplicateResourceException;
import com.bootcamp4u.exception.ResourceNotFoundException;
import com.bootcamp4u.mapper.BootcampMapper;
import com.bootcamp4u.repository.BootcampRepository;
import com.bootcamp4u.repository.UserRepository;
import com.bootcamp4u.service.BootcampService;
import com.bootcamp4u.util.SlugUtil;
import jakarta.persistence.EntityManager;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import java.util.Objects;
import java.util.UUID;

@Slf4j
@Service
@RequiredArgsConstructor
@Validated
public class BootcampServiceImpl implements BootcampService {

    private final BootcampRepository bootcampRepository;
    private final UserRepository userRepository;
    private final BootcampMapper bootcampMapper;
    private final EntityManager entityManager;

    @Override
    @Transactional
    public BootcampResponse createBootcamp(final BootcampCreateRequest request, String authenticatedUserIdentifier) {

        // 1. Generate the slug from the Title
        final String generatedSlug = SlugUtil.toSlug(request.getTitle());
        log.debug("Initiating bootcamp creation for slug: {}", generatedSlug);

        // Optional: Early fail for better UX, but not reliable for concurrency
        if (bootcampRepository.existsBySlug(generatedSlug)) {
            log.warn("Bootcamp creation failed. Slug already exists: {}", generatedSlug);
            throw new DuplicateResourceException("A bootcamp with " + generatedSlug + " slug already exists: ");
        }

        // 2. Fetch Required Dependencies and Validate Role
        final User instructor = userRepository.findByUsername(authenticatedUserIdentifier)
                .orElseThrow(() -> {
                    log.error("Authenticated user not found in database for username: {}", authenticatedUserIdentifier);
                    return new ResourceNotFoundException("Instructor profile not found.");
                });

        // Ensure the user actually has the authority to be an instructor
        if (!instructor.getRole().equals(Role.INSTRUCTOR) && !instructor.getRole().equals(Role.ADMIN)) {
            log.warn("User {} attempted to create a bootcamp without instructor privileges.", instructor.getFirstName());
            throw new AuthorizationException("The provided user is not an instructor.");
        }

        // 3. Map, Persist, and Return
        final Bootcamp bootcampToSave = bootcampMapper.toEntity(request, instructor, generatedSlug);

        try {
            final Bootcamp savedBootcamp = bootcampRepository.save(bootcampToSave);

            // Flush to ensure timestamps are generated by Hibernate
            entityManager.flush();
            // Refresh to populate the createdAt and updatedAt fields
            entityManager.refresh(savedBootcamp);

            log.info("Successfully created bootcamp with ID: {}", savedBootcamp.getId());

            // Log saved modules
            if (savedBootcamp.getSections() != null && !savedBootcamp.getSections().isEmpty()) {
                log.info("Bootcamp saved with {} course modules", savedBootcamp.getSections().size());
                savedBootcamp.getSections().forEach(module ->
                    log.debug("Saved Module ID: {}, title='{}', order={}",
                        module.getId(), module.getTitle(), module.getSequenceOrder())
                );
            }

            return bootcampMapper.toResponse(savedBootcamp);

        } catch (DataIntegrityViolationException e) {
            // This catches the database unique constraint violation if two requests try to save the same slug concurrently
            log.error("Database constraint violation for slug: {}", generatedSlug, e);
            throw new DuplicateResourceException("A bootcamp with this slug already exists: " + generatedSlug);
        }
    }

    @Override
    public PageResponse<BootcampResponse> getAllBootcamps(int page, int size) {
        // 1. Fix the zero-index issue (if frontend sends page 1, we query page 0)
         var pageNumber = page > 0 ? (page - 1) : 0;
         Pageable pageable = PageRequest.of(pageNumber, size, Sort.by(Sort.Direction.DESC, "createdAt"));

        // 2. Fetch and map the data exactly as you were doing before
         var bootcampPage = bootcampRepository.findAll(pageable).map(bootcampMapper::toResponse);

        // 3. Wrap the mapped page and its content into your custom DTO
        return new PageResponse<>(bootcampPage, bootcampPage.getContent());

    }

    @Override
    @Transactional
    public BootcampResponse getBootcampById(UUID uId) {
        // 1. Better validation: Using a dedicated validator or standard Java Objects
        Objects.requireNonNull(uId, "Bootcamp ID must not be null");

       return bootcampRepository
               .findById(uId)
               .map(bootcampMapper::toResponse)
               .orElseThrow(() -> {
                   log.error("Attempted to access non-existent bootcamp: {}", uId);
                   return new ResourceNotFoundException("Bootcamp not found");
               });
    }

    @Override
    @Transactional(readOnly = true)
    public BootcampResponse getBootcampBySlug(@NonNull  String slug) {
        Objects.requireNonNull(slug, "Bootcamp Slug must not be null");

        return bootcampRepository.findBySlug(slug)
                .map(bootcampMapper::toResponse)
                .orElseThrow(() -> {
                    log.debug("Attempted to access non-existent bootcamp with slug: {}", slug);
                    return new ResourceNotFoundException("Bootcamp not found");
                });
    }

    @Override
    public void deleteBootcamp(@NonNull UUID id) {
        // 1. Validate the input
        Objects.requireNonNull(id, "Bootcamp ID must not be null");

        // 2. Check if the bootcamp exists before attempting deletion
        if (!bootcampRepository.existsById(id)) {
            log.debug("Attempted to delete non-existent bootcamp with ID: {}", id);
            throw new ResourceNotFoundException("Bootcamp not found with ID: " + id);
        }

        // 3. Perform the deletion
        bootcampRepository.deleteById(id);
        log.debug("Successfully deleted bootcamp with ID: {}", id);
    }

    @Override
    @Transactional
    public BootcampResponse updateBootcamp(UUID id, BootcampUpdateRequest updateRequest) {
        // Defensive check: Prevent NullPointerExceptions if the controller allows nulls
        if (updateRequest == null) {
            throw new IllegalArgumentException("BootcampUpdateRequest request cannot be null");
        }

        // 1. Find the existing entity
       Bootcamp bootcamp =  bootcampRepository.findById(id)
                .orElseThrow(() -> {
            log.warn("Attempted to update non-existent bootcamp with ID: {}", id);
            return new ResourceNotFoundException("Bootcamp not found with ID: " + id);
        });

       // 2. Update the Bootcamp entity
       Bootcamp updatedBootcamp = bootcampMapper.updateEntity(bootcamp, updateRequest);

        // 3. Save bootcamp and return response
        Bootcamp savedBootcamp = bootcampRepository.save(updatedBootcamp);

        log.info("Successfully updated bootcamp with ID: {}", id);

        return bootcampMapper.toResponse(savedBootcamp);
    }

    @Override
    public PageResponse<BootcampResponse> getBootcampsByStatus(BootcampStatus status, int page, int size) {

        // 1. Safety Check: Enforce a maximum page size (e.g., max 100 items per request)
        int safeSize = Math.min(size, 25);

        // 2. Trust the 0-based index from the controller
        Pageable pageable = PageRequest.of(page, safeSize, Sort.by(Sort.Direction.DESC, "createdAt"));

        // 3. Fetch and map the data exactly as you were doing before
        Page<BootcampResponse> bootcampPage = bootcampRepository.findAllByStatus(status, pageable).map(bootcampMapper::toResponse);

        return new PageResponse<>(bootcampPage, bootcampPage.getContent());

    }
}
